#!/bin/bash

fifo="/tmp/gitbotfifo"

read line
set -- $line

max=5
num=$(git log --pretty=oneline ${1}..${2}|wc -l)
branch=${3/refs\/heads\//}
repo=$(basename `pwd`)
url="https://git.icinga.org/?p=${repo};a=commit;h="
head="https://git.icinga.org/?p=${repo};a=shortlog;h=${3}"


if [ ${num} -ge ${max} ]; then
        echo "${num} commit(s) pushed to ${repo} on branch '${branch}': ${head}" > $fifo
else
        git log --pretty=format:"%cn [${repo}|${branch}] %s | ${url}%h%n" ${1}..${2} > $fifo
fi

exit 0
